name: Simple JS execution
on: push
jobs:
  simple-hello-in-js:
    runs-on: ubuntu-latest

    steps:
      - name: Running a 3rd party action
        id: greet-step
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: YG

      - name: Output time
        run: echo "${{ steps.greet-step.outputs.time }}"

