name: Simple JS execution
on: 
  pull_request:
    types: [closed, reopened, assigned, opened]
jobs:
  simple-hello-in-js:
    runs-on: ubuntu-latest

    steps:
      - name: print github values
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          
      - name: list all files before checkout
        run: ls

      - name: checkout to the repo's particulars
        uses: actions/checkout@v3.5.2

      - name: list all files after checkout
        run: ls

      - name: Running a 3rd party action
        id: greet-step
        uses: actions/hello-world-javascript-action@v1.1
        with: 
          who-to-greet: YG

      - name: Output time
        run: echo "${{ steps.greet-step.outputs.time }}"

