name: Simple Shell Commands

on: push

jobs:
    run-simple-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello World
              run: echo "Hello, World"

            - name: Multiline Commands
              run: |
                node -v
                npm -v
            
            - name: Run python in shell
              run: |
                  print("Hello, World")
                  print("Hi, World")
              shell: python
    
    run-windows-commands:
        runs-on: windows-latest
        steps:
          - name: Get location in powershell
            run: Get-Location
          
          - name: Get location in bash
            run: pwd
            shell: bash